name: Create PR
on:
  push:
    branches:
      - 'test-create-pull-request-bump'

permissions: {}

jobs:
  prepare-release:
    env:
      TARGET_BRANCH: 'release-2.5'
      TARGET_VERSION: '2.5.0-rc1'
    permissions:
      contents: write  # for peter-evans/create-pull-request to create branch
      pull-requests: write  # for peter-evans/create-pull-request to create a PR
    name: Automatically generate version and manifests on release-2.5
    runs-on: ubuntu-22.04
    steps:
      - name: Create pull request
        uses: peter-evans/create-pull-request@4320041ed380b20e97d388d56a7fb4f9b8c20e79 # v7.0.0
        with:
          commit-message: "Bump version to 2.5.0-rc1"
          title: "Bump version to 2.5.0-rc1 on $release-2.5 branch"
          body: Updating VERSION and manifests to 2.5.0-rc1
          branch: update-version
          branch-suffix: random
          signoff: true
          labels: release


